MOSIP-25202 - fix sonar reliability issues
mosip/print pull request #251
Opened 2024-11-25 09:15 UTC by ymahtat-dev

2024-12-17 06:22 UTC, dhanendra06 requested changes

2024-12-17 06:22 UTC, dhanendra06 commented on src/main/java/io/mosip/print/service/impl/PrintServiceImpl.java
> +        String propertyValue = env.getProperty(UINCARDPASSWORD);
why we are calling two times env.getProperty(UINCARDPASSWORD)

2025-01-02 11:26 UTC, ymahtat-dev commented on src/main/java/io/mosip/print/service/impl/PrintServiceImpl.java
> +        String propertyValue = env.getProperty(UINCARDPASSWORD);
It's fixed now. Thanks for pointing it out.

2025-01-02 12:17 UTC, dhanendra06 approved these changes

2025-01-02 12:34 UTC, merged